name: Context Examples
on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "My Step"
        run: |
          echo "::group::Action & Actor"
          echo "Hello! $MY_ACTION"
          echo "Hello $MY_ACTOR"
          echo "::endgroup::
        env:
          MY_ACTION: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}