name: "Grouped Message Greeting"
on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: "Group logging"
        run: |
          echo "::group::My Group Message"
          echo "Hello"
          echo "World"
          echo "::endgroup::"
      - name: "My Env Variable"
        run: |
          echo "MY_VAL=hello it180171" >> $GITHUB_ENV
      - name: "step 2"
        run: |
          echo $MY_VAL