name: Reference Script Action

on:
  push:
    branches:
      - main 

jobs: 
  echo-input:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const path = require('path')
            const scriptPath = path.resolve('./public/script.js')
            console.log(require(scriptPath)({github, context, core}))